@startuml
title Transacción: Evento Terminar

hide footbox

!include ./style.iuml

Participant "Organizacion"  as ORGANIZACION

autonumber 1.1.1

ORGANIZACION->ORGANIZACION: Termino de la Interconsulta

@enduml