@startuml
title Transacción: Evento Revisar

hide footbox

!include ./style.iuml

Participant "Organizacion"  as ORGANIZACION

autonumber 1.1.1

ORGANIZACION->ORGANIZACION: Revision de pertinencia

@enduml